version: '2'

services:
  postgresaxon:
    image: postgres:12.1
    ports:
      - 5432
    networks:
      app_net:
        ipv4_address: 172.16.238.2
    environment: 
      POSTGRES_PASSWORD: Dupa123
      POSTGRES_DB: axondb
  axon1:
    depends_on: ['postgresaxon']
    image: axontest
    ports:
      - 7800
    networks:
      app_net:
        ipv4_address: 172.16.238.10
  axon2:
    depends_on: ['postgresaxon', 'axon1']
    image: axontest
    ports:
      - 7800
    networks:
      app_net:
        ipv4_address: 172.16.238.20
    entrypoint: java -Djava.net.preferIPv4Stack=true -jar axontest-0.0.1-SNAPSHOT.jar published_messagezxc

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
