apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: axonproducer
  name: axonproducer
  namespace: default
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: axonproducer
        jgroups: axoncluster
    spec:
      serviceAccountName: jgroups-kubeping-service-account
      containers:
        - env:
            - name: IS_PRODUCER
              value: "yes"
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_LABEL
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['jgroups']
          image: rawi666/axontest:latest
          imagePullPolicy: Always
          name: axonproducer
          ports:
            - containerPort: 7800
          resources: {}
      restartPolicy: Always
status: {}
