apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: axonconsumer
  name: axonconsumer
  namespace: default
spec:
  ports:
    - name: "7800"
      port: 7800
      targetPort: 7800
  selector:
    io.kompose.service: axonconsumer
status:
  loadBalancer: {}
