apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: postgresaxon
  name: postgresaxon
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: postgresaxon
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: axondb
        - name: POSTGRES_PASSWORD
          value: Test123
        image: postgres:12.1
        name: postgresaxon
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}
